#!/usr/bin/env bash
# Full original NPBench L matrix, using the existing collection/lifecycle owner.
set -euo pipefail

if [[ "${1:-}" == -h || "${1:-}" == --help ]]; then
    cat <<'HELP'
Usage: ./run_cova_large.sh [--plan] [RESULT_DIRECTORY]

Runs only the six CoVA routes for all 54 original benchmarks, preset L,
strict validation, 3 processes x 3 calls, sequentially on system resources.
Optional repaired variants and other systems are excluded.
Existing canonical goldens are required; no reference producer is executed.

Examples (from the NPBench root):
  ./run_cova_large.sh --plan .cache/cova-l-step8
  nohup ./run_cova_large.sh .cache/cova-l-step8 > .cache/cova-l-step8.log 2>&1 &
  # Resume an interrupted collection with the same command and directory.

By default, source this checkout's previously prepared local environment:
  .cache/native-validation/cova-integration-20260912/activate-cova.sh
Override NPBENCH_COVA_ACTIVATE with another activation file, or set it to an
empty string to use your already activated environment. Nothing is installed.
The LLVM prebuild is selected from the CoVA build's CMakeCache.txt.

Allowed controls:
  CUDA_VISIBLE_DEVICES       one GPU, default 0
  NPBENCH_TIMEOUT            whole-worker seconds, default 1800
  NPBENCH_GOLDEN_TIMEOUT     golden integrity-check seconds, default 1800
  NPBENCH_GOLDEN_CACHE       default this checkout's .cache/goldens
  NPBENCH_EXPECT_CPUS        explicit logical CPU count for a smaller allocation
  NPBENCH_PYTHON             default python from the activated environment
  NPBENCH_COVA_MONITOR_LIBRARY_DIR  optional verified NVML directory; default system

Inherited subset/retry, preset, repeat and resource-policy settings are cleared
or fixed so that this entry point always requests the full CoVA-only matrix.
--plan runs configuration/resource checks and freezes the plan, without running
benchmarks. It does not read all golden payloads to verify their integrity.
Do not edit code or change environments during collection or before resuming.

Results: collection.json, plan-summary.json, progress.tsv, per-cell raw records,
artifacts and analysis/ (generated by run_large.sh). Keep the result directory
for later comparison; no bulk export or upload is performed automatically.
Exit 1 can mean recorded workload failures: other cells still run. Exit 3 means
collection/preflight failure. Completion within one night is not guaranteed.
HELP
    exit 0
fi
plan=()
if [[ "${1:-}" == --plan ]]; then plan=(--plan); shift; fi
if [[ $# -gt 1 || "${1:-}" == -* ]]; then
    echo 'Expected [--plan] [RESULT_DIRECTORY]; see --help' >&2
    exit 2
fi
repo="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
activation="${NPBENCH_COVA_ACTIVATE-$repo/.cache/native-validation/cova-integration-20260912/activate-cova.sh}"
if [[ -n "$activation" ]]; then
    [[ -r "$activation" ]] || { echo "Activation file unavailable: $activation; see --help" >&2; exit 3; }
    # shellcheck disable=SC1090
    source "$activation"
fi
python="${NPBENCH_PYTHON:-python}"
: "${COVAPATH:?Activate CoVA first (COVAPATH is required); see --help}"
cache="$COVAPATH/build/CMakeCache.txt"
[[ -r "$cache" ]] || { echo "Missing CoVA build configuration: $cache" >&2; exit 3; }
built_llvm="$(sed -n 's/^COVA_LLVM_PREBUILD:[^=]*=//p' "$cache")"
[[ -n "$built_llvm" && -x "$built_llvm/llvm/bin/mlir-opt" ]] || {
    echo 'This launcher requires the existing CoVA LLVM prebuild recorded in CMakeCache.txt.' >&2
    exit 3
}
if [[ -n "${COVA_LLVM_PREBUILD:-}" && "$(realpath -m -- "$COVA_LLVM_PREBUILD")" != "$(realpath -m -- "$built_llvm")" ]]; then
    echo 'COVA_LLVM_PREBUILD differs from the installed CoVA build; use a matching environment.' >&2
    exit 3
fi
export COVA_LLVM_PREBUILD="$built_llvm"
export PATH="$COVA_LLVM_PREBUILD/llvm/bin:$PATH"
export PYTHONPATH="$repo${PYTHONPATH:+:$PYTHONPATH}"
export PYTHONDONTWRITEBYTECODE=1
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
# The historical activation pins NVML for an older driver. Use system monitoring
# by default; an explicit override affects monitoring only, never CUDA workers.
export NPBENCH_NVML_LIBRARY_DIR="${NPBENCH_COVA_MONITOR_LIBRARY_DIR:-}"
export NPBENCH_RESOURCE_POLICY=system NPBENCH_MEASUREMENT_ROLE=main
export NPBENCH_PRESET=L NPBENCH_FRESH_PROCESSES=2 NPBENCH_REPEATS=2
export NPBENCH_REQUIRE_GOLDEN=1
export NPBENCH_FRAMEWORKS='cova_llvm_cpu cova_llvm_cpu_serial cova_llvm_gpu cova_openmp_cpu cova_openmp_gpu cova_serial_cpu'
unset NPBENCH_BENCHMARKS NPBENCH_CASES_FILE NPBENCH_RETRY_FROM NPBENCH_RESOURCE_PROBE
export NPBENCH_TIMEOUT="${NPBENCH_TIMEOUT:-1800}"
export NPBENCH_GOLDEN_TIMEOUT="${NPBENCH_GOLDEN_TIMEOUT:-1800}"

# Fail explicitly if the catalog or imported CoVA no longer matches this task.
"$python" - "$repo" <<'PY'
import json, os, subprocess, sys
from pathlib import Path
import cova
repo = Path(sys.argv[1])
originals = [p for p in (repo / 'bench_info').glob('*.json')
             if not json.loads(p.read_text())['benchmark'].get('optional', False)]
assert len(originals) == 54, 'Original catalog changed; review the matrix before running'
assert all('L' in json.loads(p.read_text())['benchmark']['parameters'] for p in originals)
selected = set(os.environ['NPBENCH_FRAMEWORKS'].split())
assert {p.stem for p in (repo / 'framework_info').glob('cova_*.json')} == selected, 'CoVA route catalog changed'
expected = Path(os.environ['COVAPATH']).resolve()
assert Path(cova.__file__).resolve().parents[1] == expected, 'Imported CoVA is not COVAPATH'
assert not subprocess.check_output(['git', '-C', str(expected), 'status', '--porcelain'], text=True).strip(), 'Commit or isolate CoVA changes before the frozen full run'
print('Full matrix: 54 benchmarks x 6 CoVA routes; L; strict 3 x 3 lifecycle.', flush=True)
print('CoVA:', subprocess.check_output(['git', '-C', str(expected), 'rev-parse', 'HEAD'], text=True).strip(), flush=True)
PY
out="${1:-$repo/.cache/large-runs/$(date -u +%Y%m%dT%H%M%SZ)-cova-L}"
echo "Output: $out"
exec bash "$repo/run_large.sh" "${plan[@]}" cova "$out"
