#!/usr/bin/env bash
# Full CoVA L matrix with corrected ADI and separately identified helpers.
set -euo pipefail

if [[ "${1:-}" == -h || "${1:-}" == --help ]]; then
    cat <<'HELP'
Usage: ./run_cova_large.sh [--plan] [RESULT_DIRECTORY]

Runs the six CoVA routes for 54 workloads (adi_corrected replaces adi), plus
registered routes for the three explicit CoVA helpers, preset L.
Currently: 324 main cells (4 corrected-ADI routes are missing_source) plus
7 helper cells; 57 registration names, not 57
independent workloads. Original helper-target implementations remain included.
Strict validation, 3 processes x 3 calls, sequentially on system resources.
CPU routes use all allocated CPUs; GPU routes use the selected NUMA policy.
Native runtimes choose their own thread counts.
One visible GPU is used. Other optional repairs and other systems are excluded.
Existing canonical goldens are required; no reference producer is executed.

Examples (from the NPBench root):
  ./run_cova_large.sh --plan .cache/cova-l-current
  nohup ./run_cova_large.sh .cache/cova-l-current > .cache/cova-l-current.log 2>&1 &
  # Resume unchanged code/configuration with the same command and directory.
  # Use a NEW directory for this updated selection or a new CoVA revision.

By default, source this checkout's previously prepared local environment:
  .cache/native-validation/cova-integration-20260912/activate-cova.sh
Override NPBENCH_COVA_ACTIVATE with another activation file, or set it to an
empty string to use your already activated environment. Nothing is installed.
The LLVM prebuild is selected from the CoVA build's CMakeCache.txt.

Allowed controls:
  CUDA_VISIBLE_DEVICES       one GPU, default 0
  NPBENCH_GPU_NUMA_BINDING    off|cpu|cpu-memory, default cpu-memory
  NPBENCH_TIMEOUT            whole-worker seconds, default 1800
  NPBENCH_GOLDEN_TIMEOUT     golden integrity-check seconds, default 1800
  NPBENCH_GOLDEN_CACHE       default this checkout's .cache/goldens
  NPBENCH_EXPECT_CPUS        explicit logical CPU count for a smaller allocation
  NPBENCH_PYTHON             default python from the activated environment
  NPBENCH_COVA_MONITOR_LIBRARY_DIR  optional verified NVML directory; default system

Inherited subset/retry, preset, repeat and resource-policy settings are cleared
or fixed so that this entry point always requests the full CoVA-only matrix.
--plan runs configuration/resource checks and freezes the plan, without running
benchmarks. It does not read all golden payloads to verify their integrity.
Do not edit code or change environments during collection or before resuming.

The exact main/helper selection is frozen in collection.json and plan.tsv;
helper registration names remain separate and are not extra native coverage.
Results: collection.json, plan-summary.json, progress.tsv, per-cell raw records,
artifacts and analysis/ (generated by run_large.sh). Keep the result directory
for later comparison; no bulk export or upload is performed automatically.
Exit 1 can mean recorded workload failures: other cells still run. Exit 3 means
collection/preflight failure. Completion within one night is not guaranteed.
HELP
    exit 0
fi
plan=()
if [[ "${1:-}" == --plan ]]; then plan=(--plan); shift; fi
if [[ $# -gt 1 || "${1:-}" == -* ]]; then
    echo 'Expected [--plan] [RESULT_DIRECTORY]; see --help' >&2
    exit 2
fi
repo="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
activation="${NPBENCH_COVA_ACTIVATE-$repo/.cache/native-validation/cova-integration-20260912/activate-cova.sh}"
if [[ -n "$activation" ]]; then
    [[ -r "$activation" ]] || { echo "Activation file unavailable: $activation; see --help" >&2; exit 3; }
    # shellcheck disable=SC1090
    source "$activation"
fi
python="${NPBENCH_PYTHON:-python}"
: "${COVAPATH:?Activate CoVA first (COVAPATH is required); see --help}"
cache="$COVAPATH/build/CMakeCache.txt"
[[ -r "$cache" ]] || { echo "Missing CoVA build configuration: $cache" >&2; exit 3; }
built_llvm="$(sed -n 's/^COVA_LLVM_PREBUILD:[^=]*=//p' "$cache")"
[[ -n "$built_llvm" && -x "$built_llvm/llvm/bin/mlir-opt" ]] || {
    echo 'This launcher requires the existing CoVA LLVM prebuild recorded in CMakeCache.txt.' >&2
    exit 3
}
if [[ -n "${COVA_LLVM_PREBUILD:-}" && "$(realpath -m -- "$COVA_LLVM_PREBUILD")" != "$(realpath -m -- "$built_llvm")" ]]; then
    echo 'COVA_LLVM_PREBUILD differs from the installed CoVA build; use a matching environment.' >&2
    exit 3
fi
export COVA_LLVM_PREBUILD="$built_llvm"
export PATH="$COVA_LLVM_PREBUILD/llvm/bin:$PATH"
export PYTHONPATH="$repo${PYTHONPATH:+:$PYTHONPATH}"
export PYTHONDONTWRITEBYTECODE=1
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
# The historical activation pins NVML for an older driver. Use system monitoring
# by default; an explicit override affects monitoring only, never CUDA workers.
export NPBENCH_NVML_LIBRARY_DIR="${NPBENCH_COVA_MONITOR_LIBRARY_DIR:-}"
export NPBENCH_RESOURCE_POLICY=system NPBENCH_MEASUREMENT_ROLE=main
export NPBENCH_PRESET=L NPBENCH_FRESH_PROCESSES=2 NPBENCH_REPEATS=2
export NPBENCH_REQUIRE_GOLDEN=1
export NPBENCH_FRAMEWORKS='cova_llvm_cpu cova_llvm_cpu_serial cova_llvm_gpu cova_openmp_cpu cova_openmp_gpu cova_serial_cpu'
unset NPBENCH_BENCHMARKS NPBENCH_CASES_FILE NPBENCH_RETRY_FROM NPBENCH_RESOURCE_PROBE
export NPBENCH_TIMEOUT="${NPBENCH_TIMEOUT:-1800}"
export NPBENCH_GOLDEN_TIMEOUT="${NPBENCH_GOLDEN_TIMEOUT:-1800}"

# Fail explicitly if the catalog or imported CoVA no longer matches this task.
case_file="$("$python" - "$repo" <<'PY'
import hashlib, json, os, subprocess, sys
from pathlib import Path
selection_output = sys.stdout
sys.stdout = sys.stderr  # Keep optional dependency notices out of the path.
import cova
from npbench.infrastructure import Benchmark, generate_framework
repo = Path(sys.argv[1])
originals = [p for p in (repo / 'bench_info').glob('*.json')
             if not json.loads(p.read_text())['benchmark'].get('optional', False)]
assert len(originals) == 54, 'Original catalog changed; review the matrix before running'
assert all('L' in json.loads(p.read_text())['benchmark']['parameters'] for p in originals)
selected = set(os.environ['NPBENCH_FRAMEWORKS'].split())
assert {p.stem for p in (repo / 'framework_info').glob('cova_*.json')} == selected, 'CoVA route catalog changed'
expected = Path(os.environ['COVAPATH']).resolve()
assert Path(cova.__file__).resolve().parents[1] == expected, 'Imported CoVA is not COVAPATH'
assert not subprocess.check_output(['git', '-C', str(expected), 'status', '--porcelain'], text=True).strip(), 'Commit or isolate CoVA changes before the frozen full run'
# Keep all original implementation cells, except the superseded ADI formula.
main = {p.stem for p in originals}
assert 'adi' in main
main.remove('adi'); main.add('adi_corrected')
corrected = Benchmark('adi_corrected').info
assert corrected['repair']['original_benchmark'] == 'adi' and corrected['repair']['changes_reference']
assert not corrected.get('golden_reference'), 'Corrected ADI must use its own golden'
helpers = ('azimint_hist_cova_helper', 'mandelbrot2_cova_helper', 'stockham_fft_cova_helper')
rows = []
for name in sorted(main) + list(helpers):
    bench = Benchmark(name)
    assert 'L' in bench.info['parameters']
    helper = name in helpers
    if helper:
        adaptation = bench.info['adaptation']
        assert adaptation['kind'] == 'explicit_cova_helper' and not adaptation['changes_reference']
        assert bench.info['golden_reference'] == adaptation['original_benchmark']
    present = 0
    for route in sorted(selected):
        for source, label in generate_framework(route).impl_files(bench):
            if helper and not source.is_file():
                continue
            assert source.is_file() or name == 'adi_corrected', f'Missing main implementation: {name}/{route}'
            rows.append((name, route, label)); present += 1
    assert present > 0, f'No registered CoVA routes: {name}'
assert len(rows) == len(set(rows))
content = ''.join('\t'.join(row) + '\n' for row in sorted(rows))
# Content-addressed selection keeps the environment stable across resume and
# never overwrites another collection's selection. run_large owns plan freezing.
selection_dir = repo / '.cache' / 'cova-large-selections'
selection_dir.mkdir(parents=True, exist_ok=True)
selection = selection_dir / (hashlib.sha256(content.encode()).hexdigest() + '.tsv')
try:
    with selection.open('x') as stream:
        stream.write(content)
except FileExistsError:
    assert selection.read_text() == content, 'Frozen selection differs'
main_count = sum(name in main for name, _, _ in rows)
print(f'Full matrix: {len(main)} workloads x 6 routes = {main_count} main cells; '
      f'{len(rows) - main_count} separately identified helper cells; L; strict 3 x 3 lifecycle.', file=sys.stderr, flush=True)
print('Corrected ADI routes without sources remain explicit missing_source cells; no original ADI fallback.', file=sys.stderr, flush=True)
print('CoVA:', subprocess.check_output(['git', '-C', str(expected), 'rev-parse', 'HEAD'], text=True).strip(), file=sys.stderr, flush=True)
print(selection, file=selection_output)
PY
)"
export NPBENCH_CASES_FILE="$case_file"
out="${1:-$repo/.cache/large-runs/$(date -u +%Y%m%dT%H%M%SZ)-cova-L}"
echo "Output: $out"
exec bash "$repo/run_large.sh" "${plan[@]}" cova "$out"
